language: node_js
node_js:
- 0.12
sudo: required
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- sudo apt-get install -y -qq graphicsmagick
- npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
- npm install
- bower install
install: npm test
before_script:
- grunt build
script:
- echo "${TRAVIS_PULL_REQUEST}"
- echo "${TRAVIS_BRANCH}"
after_script:
- codeclimate < ./coverage/**/lcov.info
after_success:
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_USER}\n${FIREBASE_PASSWORD}"
  | firebase login;firebase deploy; fi
env:
  global:
  - secure: jG+ihItGGreVj6iR2m2GD2Ib5k4Lt6s4QTKNqV5mSDKACTuhu2f3jZSxqMxhDHhEqjXOII86IbLoslv8Rn1qqirSw34jHVphJfDN+MwuQ0mDt5p0pOfc9wtQUW/J9PePkHoPsXyGX37+TMzzSthWuJIQMpYcv1jK94dcVyBm1DmNXi3Edznyw+SiR/hugux+S6AjEk9OhEusNCLZ52LCHvUUclhH92G4t4GSJ8qDoLhpQ+JQqLNU1Sjm/aq8DHhk4tFUea7uJc79EpVT4gT1Qe4P5WswQkXEyRhEiSVvzQB9db0t1mZ3a99+swXd8lifX1NoDdtDMcyvrtr2K46xAiakji5rNbXTDPH+a2gef4yArPYUugTz9lieAyljerxrRCiz7zyGQWqtxE3DEoa8xgaCEvjbxN7eJSQumUduNRMxYiS/4jHsXZH661a16mtO51DcjgkyHPoAV0coahaRwmbwvZCtYftW+TClq5IGM/GWn77sZtLJbJ7wQhuTlBxD9wEmso2kdWt6hwIghwhE0dmteX7yJaqkYcA5Ya6vPQqJfezvP6KOsNHQ+F3JOViRAbYobbHrk7LZMstGua2UN5vI6WmNKLP5JddzqhHvmRJjaBUp8ceQRcQBm7yBjeb6Uofsr7W7K73DrMH7zkVpazDS2BWgX0k2f6+K9d8sRqQ=
  - secure: ZMfYAi1YEJ7rx0M4TumnzgS+0boaORIoru4sPxW8psJXIOV9UzhdEdfTqVdhk3SH8X2YH97M7ox4zcW9rbMuPO+Pt9uB9QtUyRjm5RnRvt0aUK3whemLod2WBOYLsC8B+eUNh3oYqzdyMex6fjTcoq6Q/vy2qXbUabTtFKxDuTx3Pc55jiFqwOs2ZsRWo+mNCqUinrv1IyRO5oIOcKsPQzOyaAydnmYWuwMygpzb1+brkBHSWNtnZWPJfv89U0UNTI0a7yXCxWpGRjX/HUzEDIlNIXt4Hw9/AidtU0CjfHhlUsipTPive0RA9pRqB0mLStfNT882Hj/RcOtep9RL9wm7xNvGKPPJYU9SUHrKLKzqfDpzVHYc8/T1JtJcqK39OO9hzM8hfUMw2lflfSOQqX7CybfX9pwZF2GYimThbkir5C0vioWdCLLePbOOUDUS1h3huC/zstoKFebLVIMoPji9HBlSiNT6CGjPgF3S6Exy9OEGvxU4YqvceVOnDnlZFS0U83EA01da2Cu3K66Y875jmzlaMJ11MN4ROX3EkO5jaTQouLLYJ6GZsI+t7hIl//kysxScsSzU31M85nqyONXRDQzmXSWm50BiOIXpPhAdX2di1uSem8YBknQWLUjxkLFc8kgfj0e17ZCdE6YyOJ1Q6moKjk+om4Hylnkhf5U=
  - secure: hfmXfaEIk6jmRE9pcyKHXYg0yWE+CXZpBR8v+YcLdIdGok2B4X92pjJKBCsffRdmOoyThZ8zYlS6UqTnM2E97lceLwuwJjFfWa1y0q7rblI3GD09U2dYZq3jDYrSUug2EVN0i3dj8x3LvKJVJ9edgoXuj5MKkLsOKY2xQOeKluJeFi1Hq3CNZQvlSfjHJ11AffI7ZtoY45eIQFBNGW97ait4R3EIlUNuCmchovik2juEpXawAnDCTUeAiG/MvJFBDsx1b78nqKXce6if1D+XtjsOIMsA1zz8N/ZLGtfmGLwzeogZugC9IDf5DKI1WRMvEkt9MbMlj87qMOHOUNUhKLYzRXD9X7V8PvBKUEiyFC1H5y1LXinc2FW7hfHF+tuEaP1MtKSSqtlAWZWG9XUVzgV/FhXzFiJGmKijMERmjdZ6dF0QF9YCSrJYGvaddk6x3bycyjLFzQQxR5IeGwuZ5NTYjLZw/ro1EVJij080SaufTKOFVs/kvg87hW03rXOChMbdJxKH9baIpA0ft4QeLbDgCq2tvohVaXAXj7U5qVrrVLSyvfjzlvozMQURP77T08UsT+H7akclB3JveU7bvtmmTCXCdNAIWV9Tt7tup24BtvmDPC9vMsOy3fZ5oMIJG4kYMQ+KcE8GdAxay9K+48F9pxiudqK+Ox40SlenBXM=
