language: node_js
node_js:
- 0.12
sudo: required
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- sudo apt-get install -y -qq graphicsmagick
- npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
- npm install
- bower install
install: npm test
before_script:
- grunt build
script:
- echo "${TRAVIS_PULL_REQUEST}"
- echo "${TRAVIS_BRANCH}"
after_script:
- codeclimate < ./coverage/**/lcov.info
after_success:
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_USER}\n${FIREBASE_PASSWORD}"
  | firebase login;firebase deploy; fi
env:
  global:
  - secure: tx1GBVwv1vpS9TQ0SSE9YDBR0m8L8H0k5//d69+09LqusVx3qComd3Dfvn6NW5EJnFYuSUDbHVFjAI4jxGuQAmJNMOmmZIcZAXt9PKbNTw/zWjVjnnJXPVwmDk2HgX08mVXbOWV+swZxp8l2iQOTsfts4LToOar3jlHzp7XfwHTAQQ9dBiHJQ55Rymyda3dJYwkD0O+LeoPEUEZXp7dxl41gsGIlpiiKTjI0wS7wQDcQfYLqY2hvEzADRcQfUJp3gZAdLxwBs7pTeJj22G5k0LikvT2FUrk9DDqDUl+7RXLaUmjonZ+zIQmsoEZb0iyNT9zkGBgXFqszplPWLADBvMYA6/YbYH5oEQ4SVl0YoALuWwB+gkT+bi2BorLDks9EjpLgzjWfLD0QdfMGLCjxq0bG2pcY0d3TawDmRtqsouU6/S+kmEQUxWgZk/5XvCvB1rPFVYWqx/+iG8TGb9W3Yqmpo+zt3magG0eufD9qHqz483qbdVTRBDVcIJhERuPlJZhJf4QaJ4UXjfStm8Q1Gz1Rm96mvUoc4UfbqteOM3JfIRaRFMbNMQOhaAjhsrgE4H/4W/KGX+Ri224uYSOAlo3YMJMmXprMZt6rEYTWRvRrN/RGrsLaCujeiqZga2wuN3YmR07QhlK+FrDrGz0lRWRYd/PcjWviTmYylQGVwjw=
  - secure: uZt+bgvPlf+/r8weXBRAsyJj+5gv05aYnbi2fyHH2qchgSGsS+ag5XBZJKO3rfXoLQmSBH6shg510+AXn4mJlEz4PP8hVMs7DNrARcUJ9rK7h/9ukV9CeMxbMGf8S4MXii/1Jb/8fFk/AOtKiVcajAc2ZYqbX8uCSRs6K4kF10ustw0r//H5m4ZuqTyLkSxY6dEfM99YyJi3iPHcdT7yvSV6Dmx1i0iioAFuX31yQzbbllols3TgOWyHkltP9eX9tS/sXAei2Vqa0yl964/gOlmxEUlyoKdnGUJg+Ov9qjozr+QafJPTZPmD7McZZOgAgzCqlQD1q2pwJDUgnsEkrTIOckiq4Oa5Fp8fFshzBqSYcYGea2pEiRtcXay8lFuclW1RRN9zKQkn8JVOLtJYdZyan8Jsf3pDvUKDyjfYy5PNiYdHgbWmxTKzPpPDY5TtsaUS46EgPciWuTNKMhvM9fCQOuoB/pAJiB1PYCOcKt9nIL9TDbjs1zezL6tVX/CYjfPAiHhjwbec3ramA7oxJbP9FmsJkWtRkyy9S5UFvwrRrlguaQJNRRxoxK5Z1pUvf7wk3I8RZfOc1UdzYsOHTGHect7ILIqutSPtfusTBA/5M9Er3So6Jl/esXwcItgGLleXUgWDWmQ1Xde/JxsNfiMPL40u7kDoNcYaA/7wGbw=
  - secure: kMdChUAJYoZq5NZq/RdjLvxg6af6oETipBb1TsoxWW19P1NKwnXnTEUdJFnQU6ylQSEc8d8FUplO6CAk/Z0eTGOv1Ym1OtU4+1109CWbqqK3selWyJPhTrjpRykv+byNEkWeRyQaiO0xW8jOruKWNd7Rr0VnkrmE52QIhraDJ8rScPqbD7RtDet4TlLi2Kal7FUS+BhU/D4zyTerzh5nfZ9mXuLVLxNlmwIfjvU547i5ghtWOWZG6t+HmYRDQnZhJKu2h2NdOl3WSS5IXWGPIwWCmxj6CZRcOfou4d/elgGqHmt/TljUtJ0HPQVEqNV+25/6PF6lpSV8aF5aCeJlDbBn/FngK0+W2+H8uZkhZYAjDETiK3SYmf5BQS0FfIC7f7MFA5nLNR413g7g6S3QgFI3zwIBw3M6tPQ3NDFyVf27iUg8lkxPagMpa1N2vHK6L7+L9G1taBOxhKIC7hUmVXJ6ToVg23tEg6YTTQ0sNFQe1/4LIEGfeFB+33uA+iN/RDf8fGtrLdRU2bXKr+gvkGLyYrznJiZ2us3zSOpUW0AlfTZ4QV22vHuxHNw5LNujajiNvx/I7pmG9Gr2T1nm5bWTVaVI4TDE0XB3D8Rs8iIZM8SxIoGud86n3271xGoNDN9JiAH/gCyLo7YU0TDwawZMzGhibtsvl2wM7f/kKU4=
