language: node_js
node_js:
- 0.12
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
install:
- npm i -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
- npm i
- bower install
before_script:
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- grunt travis
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_USER}\n${FIREBASE_PASSWORD}"
  | firebase login;firebase deploy; fi
env:
  global:
  - secure: ERsI2jV0VEGpOc/olVeyp19nVX6tOirBnQECbx5ERSue2EJh8on8+8WcmEYrusCkHnX7gDAsogFzLD3zGolaXz56ampaH59+GA9aO2EUZKKqbv3yvO4zRKvFkDbpDHu2s7hsh8rNQIcJ/y0wmGyxVYHs8DZO+AwuIELgNKhMidUDhYCX8QRCgdG+zvtZH368Fa1LCyD3JvC4J5DuLfNCsMjQS6uchiM6eEzKCk2nDvWq+6+I+cnm6+QhjkbZ0BaNw5TmksPgcjt4T4X99Y36yG8LvLPzuKuiWGzlWxFc3rBi14seAMdmY0fqIOJb/DCXDGgCymE5YJPF/T1Jng0AAKg2cBjSJQB6uNkKOiIVF6JsLgkLebpB94/cdF41lsH0sKxq0wMx7KBgRaa67hMngfZcCxrBZjM+Wu2F6Czclwa+ZjZ2e3WWp9ZnIeEsc2AM55qvZeb0iz1/pmTIVb3KqsU9GCX0ymK/iZpNIdy9U5xEm6Yl6EjhKPVqZ+hd4grb+nEum2yNsW/bQq2ZFrpJW6mPYkIUJyp4AiH4DsEDhbIAq4YXeiB6Ve5s5FFn+oDnQUDU7l1Gwyee6MxkXD455KOE0+3fcwqZY1v3a1gz5D9B+Sr7Z4oJMisDL04IG0aRRo3UUGs3wBgoO3PpNyrghNP+LDb6NvDqNA6sYw+J/3g=
  - secure: GSNIk9LfEvJzbZx7H5E1kH0Tp0W4/PXVXmuNKqdqkcPPztf2Ke3H0KHvBIGyylTd9GBQCHbuxkuq1BhZc/4Hyg6pHEEt2c3nJr8xpKE/6TjDGaGCtkeuLzjN67x0Nn7+Y6ZEypXjFLyHd+BAxP+yHFqlxsINQYeJWjlR8Fzf38qh+nl4ygGTgUNKBbnOHxrVqG0B15uA3nyl3y/Mva/pjg8yTP8cNufi72laHGy3/cMMQBzDMLFwjQIu9FuH8jcMXyduBkoHdLUJSIUTETLxE1rHzNyeribVTAN+9XNoNKrWYsTlftEx8C7+60PGhuSf5M3yDAu+72Qc1biLvbFaO7qAkb+GfYYj6lRYDAdL7M+CTxTG3hFbCYosSMU8OuJbmbb9ptgrhlbyMJ0u+tv9piXRuOHTY69BzCZJr0UpiE/9T+eRr6r8LFm0nGr0o56Y0rwU1WTiXqKQbX9mefiaDHx4zHdpMdd503GZc+Ney5u/NRWk3tuKjs9gr8PNS0OkzO35gjrQF+/b6CZPfzMQWsS77Fuw/n9CVCvdft8VmNjfUe18jCRBU0JStXmQm/9il4ntYXkiQkC1S8d2yi7xCyhKLWwlZKhPvj8K8Int1XDeHaXX+e11wr9Ymq0LfbnApvrlI5NeFo/G4iFauyLvo3sWMOZmqsRf+TP3KXFinqw=
  - secure: Aqk03VFdUlKyUp2I7fkyDHH16rQY5J88sEqfZf8IsMT7cz5DdCAdWuQEFur5Ziy10jJQyjm7NzKhvyNqUJw8Bf/XLEwkLVraAo79uUJTi8ydzsDSeuMGzEU9aSh7YUzl9hYeh4wljt78QdlIK28hGaGXZctLAFcLITMzF88i2NGAVJKcxPmYT+d4mAln49SWCZDFOjQIsN7RMCM4cXY5Fj8lKItUWxK0/9/PI/LXBG5K+24DHr91vf/vFo/B/r6seGDHCyBgPcYKuA7qWkrsNRjp7IPh+LHFRPJaJ34ruDeBsJIL5XuXKZGr+wbWiWwWP/buEZcec84wOMRL5tAvoqYGR70O5D+v99O60aOf8OBOpLpgZjICasw9hV28PflF+h8zg7hlA/tYLDC0iCMrevSdl7KMreJcu/LjoJ04Cy0k8vCmxwqCzQCLMxzKD36b3/NwUySxXTCXNzkN5U8kWAjFO52zlaIevLvjlukJO5ZRdQO+rwJxi0e3b/WLsrX2E8vybUAXW/xY9XiTcyM2tejPpY4ji0eRgLcgkrVnUDyXEF+I+4cLQKxhv5fyFP89HO1y4X4VzpuJuYTvZy3srJTE5wFRa0L9UcEjDjFuSRWIxwPjp1+eH+wD/oR610uvXuK8+3v0N1fykFx/oihh450XMcCKy+9FLTlG9ZIQcr0=
