language: node_js
node_js:
- 0.12
sudo: required
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- sudo apt-get install -y -qq graphicsmagick
- npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
- cd angularclient
- npm install
- bower install
install: npm test
before_script:
- grunt build
script:
- echo "${TRAVIS_PULL_REQUEST}"
- echo "${TRAVIS_BRANCH}"
after_script:
- codeclimate < ./coverage/**/lcov.info
after_success:
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_USER}\n${FIREBASE_PASSWORD}" | firebase login;firebase deploy; fi
env:
  global:
  - secure: DO+4GTgI3h1xI9Ows4Zru2PmKtfAUpXR7aSXkBnshEMkXhk6faahoYIZUZT+uE11YSgth0H436J3b6KJ5eJFSA62XbdiV6QN2uW2smXHRbvrx6PngrcCAuzI2P1aI6UC/Svj/4774uFGb/ZYvfSfBxBYmbHzH1ofVCGn7zh0g6Hyb65jgYKD1sTye8xfiZx1TkXXRK8Pp4MdGDlNoONXO+7uTvT7qZTqT/2M3QFrNdFLN+MVoNDS4b8Vi4/GCoHdMzFcZwT7pDDrysCLeKBSva03OrA4AOE8qToNcUoma73frmcHgo9X7E4PyrR1xjYbNrGPSUFHfOfzcEYN6OrOAPU2k6w6yjJ0AWz2k0SxoiiH7xxpqbO15wI/YZTnAJYsuAQNcHJgB6W2083DyAAQ4A62UXeCPuA1VUmudc8nfR28SuBvbO9i7OVxRt4Rp0ZeI1zTZXOuFbfYvT/aCnaMFOVVcpskZF++QQ6c6oIB07BVZ3ebqNr3Uv/V6ojImKezyoyqcQ8Cy7zNlPFIHu7asyAQJpYaOnPGoGs8A6xQvsw0lPE+QZPrToAsoyD3TKYqYAmaEMCTFNeioiG5+FKF2rh9X4CoteYciNV2TBUZ8vTYd9JrPBjbJllLLwHbIC0TcoVHaTWUVHvi5H/vUJ1b6wukW04tER5Q7DnsM9u8uCI=
  - secure: XMoqEvcUAbbdyQU5vSq3SsTtqEOK/RsA6qrvIyCBrd5i2f31KYw2pUYaHL6ivfdxO1gIT95xx1dqtoaSpy90Sf8JeUiRJE5mDhxQqdKbU5aNVu3/7GtcX4MKk9mAoTeuPKO78gyV4NvI66YwsmizFs5zGKvM2MZtlgOrJE1tLc6QjU1+2FUHn7toqw2IqPvpIV3R2lWfV2bkeCx+AdvoevPRN4VD9pY5vwuv+WrkGq5TKkP6OiOCzuTneqlNaQxhBioJMRMtZTEnXpOrFYlLoRI30uEFrp+bMT6pCwU9QnXHObYkWEYTpV4XZY4zQyJqMk9CgiS0j1FBZPYlOuYK9zk/ZzXaPPqkQziTz8PS60hQll90LU4fxy4ikQFtUvER31GDJkvNpluHq4mApnT/UYQf1us6O/Lz/RxZLzjSqmVxcquYwlQ9TJr2OrUE30u2/E4E4oiqmLVNfiKtFxoWXR0nx8dI/Fs/9+A1Z8SLHLGUr6q5Hgd1tD/bvvcezqsMBgyCCTvH9UDbqLmXLrn8xr6UetVJJctKTJZ1ckgMN167gH0FHAS7oG4Kmhb3+Umpt/0VhlUaSxajvlyR2THemlAcWOTXppw4A3YvDgAJYQLV+NVjFHDJnz2PpSm6wDN9I1STZrdzmG+ytYvdBibVMQ8uuytGmF27PB37AfKqfNY=
  - secure: I5XAcsn+/qlFBtlrmrE0n3QT4lkMVoGNizx7YyLG8LHf0yPl+2+AjxEPlAqU/D6PSU8tTZ8f7rwQBbdsrgAGzBKDcehAhGQsybq4NxgaszXMDjDQbA5WYQq/gXBiF9jIVFAtjo9S13L+kgwMLcuSqTIgMGjI035Jn+wM6q4AngUIo6itp4bdRgR5ISExzHumW9ErDHOuTgpWV8HazXZ8SrBmXFrWA6HBBLNwy0k4TYf5ZuY704PJVpvIIOtwy59ALArW8PISqlDHcKFLiG/8wmnGwMKy3abTBzGErrXZEcBxAK83ndH58wvvMNtHTje4YbmnE/laX3yAM9/rlati85I+4By52vrtmsresXh6H+2eGFm+PX6n6GAvj3DCZh5iPxiPCN+ZWxKge8cG+krya+MEL5ojzWNyVLquYSguVuARWdXrxjMtNsQioU2JZLD5RxuoO2PmJ4PvTgghnj0Rqkwekfb2xtgGJtrt8W9376lDikFKeBsGh0L7UDH/GqsxCsZHefq1AL7/doTatbBwpvpkECtpqiQyD28DF1EtHqesolUxx53S9K1ZSsFBNPOkjtYj0Ir1P++umy+ODpB1SH44Wa1zw4404tPREfPyghAIQvSl0I4/0ObDwHhm233fb3/+KQw7d1uHGo7cEFfbCe9jEpG9ckIrkvaUWZV1iWA=
